import type { Ticket } from "@/lib/types";

const now = Date.now();

export const MOCK_TICKETS: Ticket[] = [
  {
    id: "t1",
    code: "CW-1024",
    title: "学生申请缓考 - 操作系统课程",
    description: "学生因家中有事申请缓考，需教务审批。",
    type: "hitl",
    status: "open",
    priority: "high",
    level: "L2",
    assignee: "王老师",
    reporter: "user_8234",
    createdAt: now - 18 * 60_000,
    updatedAt: now - 5 * 60_000,
    slaDueAt: now + 42 * 60_000,
    tags: ["缓考", "操作系统"],
    conversationId: "c1",
  },
  {
    id: "t2",
    code: "CW-1023",
    title: "【危机】学生表达轻生念头",
    description: "AI 检测到用户消息包含敏感关键词，已触发危机干预。",
    type: "crisis",
    status: "in_progress",
    priority: "urgent",
    level: "L3",
    assignee: "李咨询师",
    reporter: "user_1290",
    createdAt: now - 32 * 60_000,
    updatedAt: now - 1 * 60_000,
    slaDueAt: now + 8 * 60_000,
    tags: ["危机", "心理", "高优"],
  },
  {
    id: "t3",
    code: "CW-1022",
    title: "用户对 AI 回答质量不满",
    description: "用户反馈学业助手答非所问，标记为「没帮助」。",
    type: "complaint",
    status: "open",
    priority: "medium",
    level: "L1",
    reporter: "user_4521",
    createdAt: now - 2 * 3600_000,
    updatedAt: now - 30 * 60_000,
    slaDueAt: now + 6 * 3600_000,
    tags: ["低质量"],
    feedbackIds: ["f1"],
  },
  {
    id: "t4",
    code: "CW-1021",
    title: "路由分析异常 - 高频 general 兜底",
    description: "近 1 小时 general 路由占比超过阈值，可能存在分类问题。",
    type: "feedback",
    status: "in_progress",
    priority: "high",
    level: "L2",
    assignee: "张工程师",
    reporter: "system",
    createdAt: now - 4 * 3600_000,
    updatedAt: now - 22 * 60_000,
    slaDueAt: now + 2 * 3600_000,
    tags: ["路由", "告警"],
  },
  {
    id: "t5",
    code: "CW-1020",
    title: "工具调用超时 - calendar_query",
    description: "calendar_query 工具 P99 超过 5s，建议优化。",
    type: "feedback",
    status: "resolved",
    priority: "medium",
    level: "L1",
    assignee: "张工程师",
    reporter: "system",
    createdAt: now - 24 * 3600_000,
    updatedAt: now - 6 * 3600_000,
    slaDueAt: now - 2 * 3600_000,
    tags: ["工具", "性能"],
  },
  {
    id: "t6",
    code: "CW-1019",
    title: "教务系统对接失败",
    description: "请假审批接口返回 500，已通知运维。",
    type: "hitl",
    status: "resolved",
    priority: "urgent",
    level: "L3",
    assignee: "运维",
    reporter: "system",
    createdAt: now - 2 * 86_400_000,
    updatedAt: now - 36 * 3600_000,
    slaDueAt: now - 36 * 3600_000,
    tags: ["教务", "运维"],
  },
  {
    id: "t7",
    code: "CW-1018",
    title: "用户请求删除对话历史",
    description: "用户行使被遗忘权，需删除所有对话数据。",
    type: "complaint",
    status: "open",
    priority: "low",
    level: "L1",
    reporter: "user_9981",
    createdAt: now - 5 * 3600_000,
    updatedAt: now - 1 * 3600_000,
    slaDueAt: now + 19 * 3600_000,
    tags: ["隐私", "GDPR"],
  },
  {
    id: "t8",
    code: "CW-1017",
    title: "【危机】学生深夜持续焦虑",
    description: "对话中检测到持续负面情绪 + 失眠表达。",
    type: "crisis",
    status: "in_progress",
    priority: "urgent",
    level: "L3",
    assignee: "李咨询师",
    reporter: "user_3345",
    createdAt: now - 50 * 60_000,
    updatedAt: now - 2 * 60_000,
    slaDueAt: now + 10 * 60_000,
    tags: ["危机", "失眠"],
  },
  {
    id: "t9",
    code: "CW-1016",
    title: "表扬：学业助手讲解非常清晰",
    description: "用户主动反馈 5 星好评。",
    type: "feedback",
    status: "closed",
    priority: "low",
    level: "L1",
    reporter: "user_1234",
    createdAt: now - 3 * 86_400_000,
    updatedAt: now - 2 * 86_400_000,
    slaDueAt: now - 2 * 86_400_000,
    tags: ["表扬"],
  },
  {
    id: "t10",
    code: "CW-1015",
    title: "提示注入尝试 - 用户尝试越狱",
    description: "检测到 'DAN 模式' 提示词注入，已阻断。",
    type: "hitl",
    status: "closed",
    priority: "high",
    level: "L2",
    assignee: "安全团队",
    reporter: "user_5678",
    createdAt: now - 4 * 86_400_000,
    updatedAt: now - 3 * 86_400_000,
    slaDueAt: now - 3 * 86_400_000,
    tags: ["安全", "提示注入"],
  },
];

export const TICKET_STATS = {
  open: 3,
  inProgress: 3,
  resolved: 2,
  closed: 2,
  breached: 1, // 已超时
  avgResponseMin: 4.2,
  avgResolveHour: 8.5,
};

export const TICKET_STATUS_INFO = {
  open: { name: "待处理", color: "#3B82F6" },
  in_progress: { name: "处理中", color: "#F59E0B" },
  resolved: { name: "已完成", color: "#10B981" },
  closed: { name: "已取消", color: "#6B7280" },
};

export const TICKET_PRIORITY_INFO = {
  low: { name: "低", color: "#6B7280" },
  medium: { name: "中", color: "#3B82F6" },
  high: { name: "高", color: "#F59E0B" },
  urgent: { name: "紧急", color: "#EF4444" },
};

export const TICKET_TYPE_INFO = {
  hitl: { name: "HITL 升级", color: "#3B82F6", icon: "🤝" },
  crisis: { name: "危机干预", color: "#EF4444", icon: "🚨" },
  complaint: { name: "投诉反馈", color: "#F59E0B", icon: "😤" },
  feedback: { name: "用户反馈", color: "#8B5CF6", icon: "💬" },
};
