// 技能市场 - 模拟数据

export type SkillCategory = "tool" | "data" | "cognitive" | "creative";
export type ExecutionMode = "AUTO" | "ASK_CONFIRM" | "INTERACTIVE";

export type Skill = {
  id: string;
  name: string;
  description: string;
  category: SkillCategory;
  icon: string;
  enabled: boolean;
  installed: boolean;
  calls: number;
  successRate: number;
  rating: number;
  executionMode: ExecutionMode;
  author: string;
  version: string;
  tags: string[];
  example: string;
  history: { ts: number; user: string; success: boolean; durationMs: number }[];
  permissions: string[];
  createdAt: number;
};

export const CATEGORY_INFO: Record<
  SkillCategory,
  { name: string; emoji: string; color: string; bg: string }
> = {
  tool: { name: "工具", emoji: "🔧", color: "text-info", bg: "bg-info/10" },
  data: { name: "数据", emoji: "📊", color: "text-success", bg: "bg-success/10" },
  cognitive: { name: "认知", emoji: "🧠", color: "text-primary", bg: "bg-primary/10" },
  creative: { name: "创作", emoji: "✨", color: "text-warning", bg: "bg-warning/10" },
};

export const EXECUTION_MODE_INFO: Record<
  ExecutionMode,
  { name: string; description: string; tone: "info" | "warning" | "secondary" }
> = {
  AUTO: { name: "自动执行", description: "无需确认直接运行", tone: "info" },
  ASK_CONFIRM: { name: "需确认", description: "执行前向用户确认", tone: "warning" },
  INTERACTIVE: { name: "交互式", description: "多轮交互执行", tone: "secondary" },
};

const now = Date.now();

export const MOCK_SKILLS: Skill[] = [
  {
    id: "sk_web_search",
    name: "联网搜索",
    description: "实时搜索互联网最新信息，集成多源学术资源、新闻、博客。",
    category: "tool",
    icon: "🔍",
    enabled: true,
    installed: true,
    calls: 12_840,
    successRate: 98.2,
    rating: 4.8,
    executionMode: "AUTO",
    author: "Workbench Team",
    version: "2.4.1",
    tags: ["搜索", "实时", "学术"],
    example: 'search("2026 机器学习最新论文")',
    history: [
      { ts: now - 3_600_000, user: "user_8234", success: true, durationMs: 1240 },
      { ts: now - 7_200_000, user: "user_1290", success: true, durationMs: 980 },
      { ts: now - 14_400_000, user: "user_4521", success: true, durationMs: 1620 },
      { ts: now - 86_400_000, user: "user_9981", success: false, durationMs: 3200 },
    ],
    permissions: ["网络访问", "读取公开内容"],
    createdAt: now - 90 * 86_400_000,
  },
  {
    id: "sk_calendar",
    name: "日历查询",
    description: "查询校内课程表、放假安排、个人日程。",
    category: "tool",
    icon: "📅",
    enabled: true,
    installed: true,
    calls: 8_520,
    successRate: 96.5,
    rating: 4.6,
    executionMode: "AUTO",
    author: "教务处集成",
    version: "1.8.0",
    tags: ["日程", "教务"],
    example: 'calendar_query("下周三的课程")',
    history: [
      { ts: now - 1_800_000, user: "user_3345", success: true, durationMs: 320 },
      { ts: now - 5_400_000, user: "user_8234", success: true, durationMs: 280 },
    ],
    permissions: ["读取教务数据"],
    createdAt: now - 120 * 86_400_000,
  },
  {
    id: "sk_translate",
    name: "学术翻译",
    description: "中英文学术论文双向翻译，保留公式和引用格式。",
    category: "tool",
    icon: "🌐",
    enabled: true,
    installed: true,
    calls: 4_320,
    successRate: 94.1,
    rating: 4.5,
    executionMode: "AUTO",
    author: "Workbench Team",
    version: "3.1.2",
    tags: ["翻译", "学术"],
    example: 'translate("abstract", "en")',
    history: [
      { ts: now - 4_320_000, user: "user_5678", success: true, durationMs: 2100 },
      { ts: now - 10_800_000, user: "user_1234", success: true, durationMs: 1980 },
    ],
    permissions: [],
    createdAt: now - 200 * 86_400_000,
  },
  {
    id: "sk_sql",
    name: "数据库查询",
    description: "自然语言转 SQL，自动查询教学数据库（成绩、出勤）。",
    category: "data",
    icon: "🗄️",
    enabled: true,
    installed: true,
    calls: 6_180,
    successRate: 92.3,
    rating: 4.4,
    executionMode: "ASK_CONFIRM",
    author: "数据团队",
    version: "2.0.5",
    tags: ["SQL", "数据库", "教务"],
    example: 'query("计算机系大二的平均GPA")',
    history: [
      { ts: now - 1_800_000, user: "user_8234", success: true, durationMs: 480 },
      { ts: now - 7_200_000, user: "user_1290", success: false, durationMs: 220 },
    ],
    permissions: ["读取教学数据"],
    createdAt: now - 60 * 86_400_000,
  },
  {
    id: "sk_chart",
    name: "可视化生成",
    description: "根据数据自动生成柱状图、折线图、饼图、热力图。",
    category: "data",
    icon: "📈",
    enabled: true,
    installed: true,
    calls: 3_240,
    successRate: 97.8,
    rating: 4.7,
    executionMode: "AUTO",
    author: "Workbench Team",
    version: "1.5.0",
    tags: ["图表", "可视化"],
    example: 'chart({type: "bar", data: [...]})',
    history: [{ ts: now - 2_700_000, user: "user_4521", success: true, durationMs: 620 }],
    permissions: [],
    createdAt: now - 45 * 86_400_000,
  },
  {
    id: "sk_pdf_parser",
    name: "PDF 解析",
    description: "提取 PDF 中的文本、表格、公式，生成结构化摘要。",
    category: "data",
    icon: "📄",
    enabled: false,
    installed: true,
    calls: 1_890,
    successRate: 89.2,
    rating: 4.2,
    executionMode: "AUTO",
    author: "Workbench Team",
    version: "2.2.0",
    tags: ["PDF", "解析", "文档"],
    example: 'parse_pdf("paper.pdf")',
    history: [{ ts: now - 86_400_000, user: "user_9981", success: true, durationMs: 3400 }],
    permissions: ["读取文件"],
    createdAt: now - 80 * 86_400_000,
  },
  {
    id: "sk_knowledge_graph",
    name: "知识图谱",
    description: "构建学科知识图谱，可视化概念之间的关系。",
    category: "cognitive",
    icon: "🕸️",
    enabled: true,
    installed: true,
    calls: 2_140,
    successRate: 95.6,
    rating: 4.9,
    executionMode: "INTERACTIVE",
    author: "学术团队",
    version: "1.2.0",
    tags: ["图谱", "知识", "可视化"],
    example: 'build_graph("数据结构")',
    history: [{ ts: now - 3_600_000, user: "user_8234", success: true, durationMs: 2100 }],
    permissions: [],
    createdAt: now - 30 * 86_400_000,
  },
  {
    id: "sk_concept_explain",
    name: "概念解释",
    description: "针对学术概念生成多层次解释（初学者/进阶/专家）。",
    category: "cognitive",
    icon: "💡",
    enabled: true,
    installed: true,
    calls: 5_620,
    successRate: 96.4,
    rating: 4.6,
    executionMode: "AUTO",
    author: "Workbench Team",
    version: "2.0.1",
    tags: ["解释", "教学"],
    example: 'explain("二项分布", level="beginner")',
    history: [{ ts: now - 1_800_000, user: "user_3345", success: true, durationMs: 880 }],
    permissions: [],
    createdAt: now - 50 * 86_400_000,
  },
  {
    id: "sk_mindmap",
    name: "思维导图",
    description: "一键生成结构化思维导图，支持导出 Markdown / 图片。",
    category: "creative",
    icon: "🗺️",
    enabled: true,
    installed: true,
    calls: 1_960,
    successRate: 94.0,
    rating: 4.5,
    executionMode: "AUTO",
    author: "Workbench Team",
    version: "1.3.2",
    tags: ["导图", "结构化"],
    example: 'mindmap("机器学习")',
    history: [{ ts: now - 5_400_000, user: "user_5678", success: true, durationMs: 1400 }],
    permissions: [],
    createdAt: now - 25 * 86_400_000,
  },
  {
    id: "sk_email_draft",
    name: "邮件草稿",
    description: "根据场景生成专业邮件草稿（请假、咨询、感谢等）。",
    category: "creative",
    icon: "✉️",
    enabled: true,
    installed: true,
    calls: 2_780,
    successRate: 97.1,
    rating: 4.4,
    executionMode: "ASK_CONFIRM",
    author: "Workbench Team",
    version: "1.1.5",
    tags: ["邮件", "办公"],
    example: 'draft_email({to: "teacher", topic: "请假"})',
    history: [{ ts: now - 7_200_000, user: "user_1234", success: true, durationMs: 720 }],
    permissions: ["发送邮件"],
    createdAt: now - 70 * 86_400_000,
  },
  {
    id: "sk_code_runner",
    name: "代码执行",
    description: "沙箱中安全执行 Python / JS 代码，输出结果与图表。",
    category: "tool",
    icon: "▶️",
    enabled: false,
    installed: false,
    calls: 0,
    successRate: 91.5,
    rating: 4.3,
    executionMode: "ASK_CONFIRM",
    author: "Workbench Team",
    version: "1.0.0",
    tags: ["代码", "沙箱", "Python"],
    example: 'run_code("python", "import numpy as np")',
    history: [],
    permissions: ["执行代码", "访问网络"],
    createdAt: now - 10 * 86_400_000,
  },
  {
    id: "sk_image_gen",
    name: "图像生成",
    description: "根据文字描述生成插画、示意图、概念图。",
    category: "creative",
    icon: "🎨",
    enabled: false,
    installed: false,
    calls: 0,
    successRate: 88.0,
    rating: 4.1,
    executionMode: "ASK_CONFIRM",
    author: "Workbench Team",
    version: "0.9.0",
    tags: ["图像", "AI 绘画"],
    example: 'generate_image("校园风光")',
    history: [],
    permissions: ["调用 AI 模型"],
    createdAt: now - 5 * 86_400_000,
  },
];

export const SKILL_STATS = {
  total: MOCK_SKILLS.length,
  enabled: MOCK_SKILLS.filter((s) => s.enabled).length,
  calls: MOCK_SKILLS.reduce((sum, s) => sum + s.calls, 0),
  popular: [...MOCK_SKILLS].sort((a, b) => b.calls - a.calls)[0]?.name ?? "—",
};
