// 用户管理 - 模拟数据

export type UserRole = "student" | "teacher" | "admin" | "counselor";
export type UserStatus = "active" | "disabled" | "pending";
export type UserRegisteredAt = "today" | "week" | "month" | "year" | "older";

export type User = {
  id: string;
  username: string;
  email: string;
  name: string;
  role: UserRole;
  status: UserStatus;
  avatarColor: string;
  sessions: number;
  messages: number;
  registeredAt: number;
  lastActiveAt: number;
  department: string;
  major?: string;
  studentId?: string;
  staffId?: string;
  phone?: string;
  lastLoginIp: string;
  memoryCount: number;
};

export const ROLE_INFO: Record<
  UserRole,
  { name: string; tone: "default" | "info" | "warning" | "success" }
> = {
  student: { name: "学生", tone: "info" },
  teacher: { name: "教师", tone: "success" },
  admin: { name: "管理员", tone: "warning" },
  counselor: { name: "咨询师", tone: "default" },
};

export const STATUS_INFO: Record<
  UserStatus,
  { name: string; tone: "success" | "destructive" | "warning" }
> = {
  active: { name: "活跃", tone: "success" },
  disabled: { name: "禁用", tone: "destructive" },
  pending: { name: "待激活", tone: "warning" },
};

const now = Date.now();
const min = 60_000;
const hour = 60 * min;
const day = 24 * hour;

const departments = [
  "计算机学院",
  "电子工程学院",
  "数学科学学院",
  "外国语学院",
  "心理辅导中心",
  "教务处",
  "信息中心",
];

export const MOCK_USERS: User[] = [
  {
    id: "u_8234",
    username: "liming",
    email: "liming@school.edu",
    name: "李明",
    role: "student",
    status: "active",
    avatarColor: "bg-info/15 text-info",
    sessions: 142,
    messages: 1840,
    registeredAt: now - 180 * day,
    lastActiveAt: now - 12 * min,
    department: "计算机学院",
    major: "软件工程",
    studentId: "2021034",
    phone: "138****2341",
    lastLoginIp: "10.0.1.42",
    memoryCount: 28,
  },
  {
    id: "u_1290",
    username: "wangxue",
    email: "wangxue@school.edu",
    name: "王雪",
    role: "student",
    status: "active",
    avatarColor: "bg-success/15 text-success",
    sessions: 98,
    messages: 1240,
    registeredAt: now - 90 * day,
    lastActiveAt: now - 2 * hour,
    department: "电子工程学院",
    major: "电子信息",
    studentId: "2022018",
    phone: "139****7821",
    lastLoginIp: "10.0.1.78",
    memoryCount: 19,
  },
  {
    id: "u_4521",
    username: "zhangwei",
    email: "zhangwei@school.edu",
    name: "张伟",
    role: "student",
    status: "active",
    avatarColor: "bg-warning/15 text-warning",
    sessions: 76,
    messages: 920,
    registeredAt: now - 60 * day,
    lastActiveAt: now - 30 * min,
    department: "数学科学学院",
    major: "应用数学",
    studentId: "2022034",
    phone: "137****3345",
    lastLoginIp: "10.0.2.18",
    memoryCount: 12,
  },
  {
    id: "u_9981",
    username: "liuyang",
    email: "liuyang@school.edu",
    name: "刘洋",
    role: "student",
    status: "disabled",
    avatarColor: "bg-muted text-muted-foreground",
    sessions: 12,
    messages: 88,
    registeredAt: now - 200 * day,
    lastActiveAt: now - 45 * day,
    department: "外国语学院",
    major: "英语",
    studentId: "2020012",
    phone: "136****9012",
    lastLoginIp: "10.0.1.105",
    memoryCount: 4,
  },
  {
    id: "u_3345",
    username: "chensi",
    email: "chensi@school.edu",
    name: "陈思",
    role: "student",
    status: "active",
    avatarColor: "bg-primary/15 text-primary",
    sessions: 215,
    messages: 3120,
    registeredAt: now - 240 * day,
    lastActiveAt: now - 4 * min,
    department: "计算机学院",
    major: "人工智能",
    studentId: "2021008",
    phone: "135****5567",
    lastLoginIp: "10.0.1.22",
    memoryCount: 52,
  },
  {
    id: "u_5678",
    username: "yangguang",
    email: "yangguang@school.edu",
    name: "杨光",
    role: "student",
    status: "pending",
    avatarColor: "bg-warning/15 text-warning",
    sessions: 0,
    messages: 0,
    registeredAt: now - 2 * hour,
    lastActiveAt: now - 2 * hour,
    department: "电子工程学院",
    major: "通信工程",
    studentId: "2024042",
    phone: "188****1122",
    lastLoginIp: "—",
    memoryCount: 0,
  },
  {
    id: "u_1234",
    username: "wang_teacher",
    email: "wang@school.edu",
    name: "王老师",
    role: "teacher",
    status: "active",
    avatarColor: "bg-success/15 text-success",
    sessions: 64,
    messages: 480,
    registeredAt: now - 365 * day,
    lastActiveAt: now - 18 * min,
    department: "计算机学院",
    staffId: "T-10034",
    phone: "138****0001",
    lastLoginIp: "10.0.10.5",
    memoryCount: 8,
  },
  {
    id: "u_2345",
    username: "zhang_professor",
    email: "zhang@school.edu",
    name: "张教授",
    role: "teacher",
    status: "active",
    avatarColor: "bg-info/15 text-info",
    sessions: 48,
    messages: 320,
    registeredAt: now - 500 * day,
    lastActiveAt: now - 1 * hour,
    department: "数学科学学院",
    staffId: "T-10021",
    phone: "139****0002",
    lastLoginIp: "10.0.10.12",
    memoryCount: 5,
  },
  {
    id: "u_3456",
    username: "li_phd",
    email: "li@school.edu",
    name: "李博士",
    role: "teacher",
    status: "active",
    avatarColor: "bg-primary/15 text-primary",
    sessions: 32,
    messages: 240,
    registeredAt: now - 720 * day,
    lastActiveAt: now - 3 * hour,
    department: "电子工程学院",
    staffId: "T-10015",
    phone: "137****0003",
    lastLoginIp: "10.0.10.18",
    memoryCount: 3,
  },
  {
    id: "u_4567",
    username: "admin_zhao",
    email: "zhao@school.edu",
    name: "赵磊",
    role: "admin",
    status: "active",
    avatarColor: "bg-warning/15 text-warning",
    sessions: 88,
    messages: 220,
    registeredAt: now - 600 * day,
    lastActiveAt: now - 5 * min,
    department: "信息中心",
    staffId: "A-00001",
    phone: "138****9001",
    lastLoginIp: "10.0.0.1",
    memoryCount: 2,
  },
  {
    id: "u_5677",
    username: "admin_zhou",
    email: "zhou@school.edu",
    name: "周婷",
    role: "admin",
    status: "active",
    avatarColor: "bg-info/15 text-info",
    sessions: 24,
    messages: 80,
    registeredAt: now - 300 * day,
    lastActiveAt: now - 1 * day,
    department: "教务处",
    staffId: "A-00002",
    phone: "139****9002",
    lastLoginIp: "10.0.0.8",
    memoryCount: 1,
  },
  {
    id: "u_6789",
    username: "counselor_huang",
    email: "huang@school.edu",
    name: "黄子轩",
    role: "counselor",
    status: "active",
    avatarColor: "bg-primary/15 text-primary",
    sessions: 156,
    messages: 1820,
    registeredAt: now - 400 * day,
    lastActiveAt: now - 8 * min,
    department: "心理辅导中心",
    staffId: "C-00012",
    phone: "135****9003",
    lastLoginIp: "10.0.0.20",
    memoryCount: 6,
  },
  {
    id: "u_7890",
    username: "counselor_lin",
    email: "lin@school.edu",
    name: "林小雨",
    role: "counselor",
    status: "active",
    avatarColor: "bg-success/15 text-success",
    sessions: 92,
    messages: 1140,
    registeredAt: now - 280 * day,
    lastActiveAt: now - 2 * hour,
    department: "心理辅导中心",
    staffId: "C-00018",
    phone: "136****9004",
    lastLoginIp: "10.0.0.22",
    memoryCount: 4,
  },
  {
    id: "u_8901",
    username: "wuzhiqiang",
    email: "wu@school.edu",
    name: "吴志强",
    role: "student",
    status: "active",
    avatarColor: "bg-success/15 text-success",
    sessions: 38,
    messages: 460,
    registeredAt: now - 30 * day,
    lastActiveAt: now - 6 * hour,
    department: "计算机学院",
    major: "信息安全",
    studentId: "2023056",
    phone: "139****7711",
    lastLoginIp: "10.0.3.45",
    memoryCount: 8,
  },
  {
    id: "u_9012",
    username: "xumengqi",
    email: "xu@school.edu",
    name: "徐梦琪",
    role: "student",
    status: "pending",
    avatarColor: "bg-warning/15 text-warning",
    sessions: 0,
    messages: 0,
    registeredAt: now - 30 * min,
    lastActiveAt: now - 30 * min,
    department: "外国语学院",
    major: "翻译",
    studentId: "2024078",
    phone: "186****0011",
    lastLoginIp: "—",
    memoryCount: 0,
  },
];

export const USER_STATS = {
  total: MOCK_USERS.length,
  active: MOCK_USERS.filter((u) => u.status === "active").length,
  disabled: MOCK_USERS.filter((u) => u.status === "disabled").length,
  todayNew: MOCK_USERS.filter((u) => u.registeredAt > now - day).length,
};

export const REGISTRATION_RANGES: { id: UserRegisteredAt | "all"; label: string }[] = [
  { id: "all", label: "全部时间" },
  { id: "today", label: "今日" },
  { id: "week", label: "本周" },
  { id: "month", label: "本月" },
  { id: "year", label: "今年" },
  { id: "older", label: "更早" },
];

export const departmentsList = departments;
