/**
 * 图标系统（v8 Lego · 借皮图标）
 *
 * 设计原则：
 *   1. 业务方只 import 一个图标名（如 <IconHome />），不直接接触底层库
 *   2. 根据"借皮场景"自动选用对应图标库的对应 weight
 *   3. 缺图时 fallback 到 lucide-react
 *   4. size 默认 16，可由父级 className 覆盖
 *
 * 用法：
 *   import { IconHome } from "@/components/icons";
 *   <IconHome className="h-4 w-4" />
 *   <IconHome skin="chatgpt" />  // 强制借皮
 *   <IconHome weight="duotone" /> // 强制 weight
 */

import { cn } from "@/lib/utils";
import * as Geist from "@geist-ui/icons";
import * as Phosphor from "@phosphor-icons/react";
import * as LucideAll from "lucide-react";
import type React from "react";
import { type CSSProperties, type ComponentType, type SVGProps, forwardRef } from "react";

/* ---------- 类型 ---------- */

export type IconSkin =
  | "default"
  | "linear"
  | "chatgpt"
  | "notion"
  | "vercel"
  | "grafana"
  | "github"
  | "admin"
  | "flywheel"
  | "analysis"
  | "evaluation";

export type IconWeight = "regular" | "bold" | "fill" | "duotone" | "light" | "thin";

export type IconProps = SVGProps<SVGSVGElement> & {
  /** 借皮场景，决定 weight */
  skin?: IconSkin;
  /** 图标 weight（覆盖 skin 默认） */
  weight?: IconWeight;
  /** 像素尺寸（默认 16） */
  size?: number;
  /** 强制从指定库取 */
  source?: "phosphor" | "geist" | "lucide" | "auto";
};

/** 通用图标组件类型（业务方用，替代 lucide 的 LucideIcon） */
export type IconComponent = ComponentType<{
  className?: string;
  size?: number;
  style?: CSSProperties;
  ref?: React.Ref<SVGSVGElement>;
}>;

const SKIN_TO_WEIGHT: Record<IconSkin, IconWeight> = {
  default: "regular",
  linear: "regular",
  chatgpt: "bold",
  notion: "light",
  vercel: "regular",
  grafana: "fill",
  github: "regular",
  admin: "regular",
  flywheel: "regular",
  analysis: "regular",
  evaluation: "regular",
};

function toPascal(input: string): string {
  return input
    .replace(/[-_\s]+(.)?/g, (_m, c: string | undefined) => (c ? c.toUpperCase() : ""))
    .replace(/^(.)/, (m) => m.toUpperCase());
}

type AnyIcon = ComponentType<Record<string, unknown>>;
const _Phosphor = Phosphor as unknown as Record<string, AnyIcon>;
const _Geist = Geist as unknown as Record<string, AnyIcon>;
const _Lucide = LucideAll as unknown as Record<string, AnyIcon>;

function resolveIcon(
  name: string,
  weight: IconWeight,
  source: "phosphor" | "geist" | "lucide" | "auto",
  size: number,
  className: string | undefined,
  style: CSSProperties | undefined,
  extraProps: Record<string, unknown> = {},
): React.ReactNode {
  const passProps = { size, weight, className, style, ...extraProps } as Record<string, unknown>;

  if (source === "phosphor" || source === "auto") {
    const P = _Phosphor[toPascal(name)] ?? _Phosphor[name];
    if (P) return <P {...passProps} />;
  }

  if (source === "geist" || source === "auto") {
    const G = _Geist[toPascal(name)] ?? _Geist[name];
    if (G) return <G size={size} className={className} style={style} {...extraProps} />;
  }

  const L = _Lucide[toPascal(name)] ?? _Lucide[name];
  if (L) {
    return (
      <L className={className} style={{ width: size, height: size, ...style }} {...extraProps} />
    );
  }

  const F = _Lucide.Activity;
  return (
    <F className={className} style={{ width: size, height: size, ...style }} {...extraProps} />
  );
}

export function Icon({
  name,
  skin = "default",
  weight: weightProp,
  size = 16,
  source = "auto",
  className,
  style,
}: IconProps & { name: string }) {
  const weight = weightProp ?? SKIN_TO_WEIGHT[skin];
  return resolveIcon(name, weight, source, size, className, style);
}

/* ---------- 命名导出 ---------- */

type NamedIcon = ComponentType<
  Partial<Omit<IconProps, "name">> & { ref?: React.Ref<SVGSVGElement> }
>;

function createNamedIcon(name: string): NamedIcon {
  const Comp = forwardRef<SVGSVGElement, Partial<Omit<IconProps, "name">>>(
    function IconImpl(props, ref) {
      const {
        skin = "default",
        weight: weightProp,
        size = 16,
        source = "auto",
        className,
        style,
        ...rest
      } = props;
      const weight = weightProp ?? SKIN_TO_WEIGHT[skin];
      return resolveIcon(name, weight, source, size, className, style, {
        ...(rest as Record<string, unknown>),
        ref,
      });
    },
  );
  Comp.displayName = `Icon${toPascal(name)}`;
  return Comp as unknown as NamedIcon;
}

/* 业务用到的图标（按 grep 出来的真实使用表 + 缺图补全） */
const ICON_NAMES = [
  "Activity",
  "Airplay",
  "AlertCircle",
  "AlertOctagon",
  "AlertTriangle",
  "AlignCenter",
  "AlignJustify",
  "AlignLeft",
  "AlignRight",
  "Anchor",
  "Archive",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "ArrowUpRight",
  "ArrowUUpLeft",
  "ArrowsClockwise",
  "ArrowsCounterClockwise",
  "At",
  "BarChart",
  "BarChart2",
  "BarChart3",
  "Battery",
  "Bell",
  "BellRinging",
  "Block",
  "Bluetooth",
  "Book",
  "BookMarked",
  "Bookmark",
  "Bot",
  "Box",
  "Brackets",
  "Brain",
  "Briefcase",
  "Calendar",
  "Camera",
  "ChartLine",
  "ChartPie",
  "ChatCircle",
  "ChatSquare",
  "Check",
  "CheckCheck",
  "CheckCircle",
  "CheckCircle2",
  "Checklist",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronsLeft",
  "ChevronsRight",
  "Circle",
  "CircleAlert",
  "CircleCheck",
  "CircleDashed",
  "CircleDot",
  "CircleHelp",
  "Clock",
  "ClockCounterClockwise",
  "Code",
  "Code2",
  "Command",
  "Compass",
  "Construction",
  "Copy",
  "Cpu",
  "CreditCard",
  "Crop",
  "Crosshair",
  "Database",
  "DeviceMobile",
  "Diamond",
  "DotsSixVertical",
  "DotsThree",
  "DotsThreeVertical",
  "Download",
  "Dribbble",
  "Edit",
  "Edit3",
  "Eraser",
  "ExternalLink",
  "Eye",
  "EyeOff",
  "File",
  "FileText",
  "Filter",
  "Flag",
  "Flame",
  "FlaskConical",
  "Folder",
  "FolderOpen",
  "Frown",
  "Funnel",
  "Gauge",
  "Gear",
  "Gift",
  "GitBranch",
  "GitCommit",
  "GitMerge",
  "GitPullRequest",
  "GithubLogo",
  "Globe",
  "GraduationCap",
  "Grid",
  "GripVertical",
  "HardDrive",
  "Hash",
  "Headphones",
  "Heart",
  "HelpCircle",
  "Hexagon",
  "History",
  "Home",
  "Hourglass",
  "HourglassMedium",
  "House",
  "Image",
  "Inbox",
  "Info",
  "Key",
  "KeyRound",
  "Keyboard",
  "Languages",
  "Laptop",
  "Layers",
  "Layout",
  "LayoutDashboard",
  "LayoutGrid",
  "LifeBuoy",
  "Lightbulb",
  "Lightning",
  "LightningSlash",
  "Link",
  "List",
  "ListChecks",
  "ListTree",
  "Loader",
  "Loader2",
  "Lock",
  "LogIn",
  "LogOut",
  "Mail",
  "MagnifyingGlass",
  "Map",
  "MapPin",
  "Maximize",
  "Menu",
  "MessageCircle",
  "MessageCirclePlus",
  "MessageSquare",
  "Mic",
  "MicOff",
  "Minimize",
  "Minus",
  "Monitor",
  "Moon",
  "MoreHorizontal",
  "MoreVertical",
  "Mouse",
  "Move",
  "Music",
  "Navigation",
  "Network",
  "Package",
  "Palette",
  "PanelRightOpen",
  "Paperclip",
  "PaperPlaneTilt",
  "Pause",
  "Pencil",
  "Percent",
  "Phone",
  "PieChart",
  "Pin",
  "Play",
  "Plug",
  "Plus",
  "Power",
  "Printer",
  "QrCode",
  "Question",
  "RefreshCw",
  "Repeat",
  "Repeat2",
  "Reply",
  "Rocket",
  "RotateCcw",
  "Rss",
  "Save",
  "Scales",
  "Scan",
  "Search",
  "Send",
  "Server",
  "Settings",
  "Share",
  "ShareNetwork",
  "Shield",
  "ShieldAlert",
  "ShieldCheck",
  "ShieldOff",
  "ShieldSlash",
  "WarningOctagon",
  "ShoppingBag",
  "ShoppingCart",
  "Shuffle",
  "Sidebar",
  "Smile",
  "SkipBack",
  "SkipForward",
  "SlackLogo",
  "Sliders",
  "Smartphone",
  "Sparkle",
  "Sparkles",
  "SpeakerHigh",
  "SpeakerSimpleHigh",
  "SpeakerSlash",
  "Spinner",
  "SpinnerGap",
  "Square",
  "SquaresFour",
  "Stack",
  "Star",
  "StopCircle",
  "Sun",
  "Sunrise",
  "Table",
  "Tablet",
  "Tag",
  "Target",
  "Terminal",
  "TestTube",
  "TextT",
  "ThumbsDown",
  "ThumbsUp",
  "Ticket",
  "Timer",
  "ToggleLeft",
  "ToggleRight",
  "Trash",
  "Trash2",
  "TrashSimple",
  "TrendDown",
  "TrendUp",
  "TrendingDown",
  "TrendingUp",
  "TreeStructure",
  "TrelloLogo",
  "Truck",
  "Tv",
  "Umbrella",
  "Underline",
  "Undo",
  "Upload",
  "User",
  "UserCheck",
  "UserCog",
  "UserGear",
  "UserCircleGear",
  "UserMinus",
  "UserPlus",
  "Users",
  "Video",
  "VideoCamera",
  "VideoCameraSlash",
  "VideoOff",
  "Volume",
  "Volume2",
  "VolumeX",
  "Wallet",
  "Wand",
  "Wand2",
  "Watch",
  "Waves",
  "Wifi",
  "WifiHigh",
  "WifiSlash",
  "Wind",
  "Workflow",
  "Wrench",
  "X",
  "XCircle",
  "Youtube",
  "YoutubeLogo",
  "Zap",
  "ZapOff",
];

const icons: Record<string, NamedIcon> = {};
for (const n of ICON_NAMES) {
  icons[`Icon${n}`] = createNamedIcon(n);
}

void cn;

/* 动态生成命名导出
 * 用 Proxy 拦截 import 访问，未在 icons 中的名字返回 fallback
 */
export const _registry = new Proxy(icons, {
  get(target, prop: string) {
    if (prop in target) return target[prop];
    console.warn(`[icons] Icon "${prop}" not pre-registered, using runtime fallback`);
    return createNamedIcon(prop);
  },
});

/* 静态导出：让 Vite/Webpack 保留这些命名 */
export const {
  IconActivity,
  IconAirplay,
  IconAlertCircle,
  IconAlertOctagon,
  IconAlertTriangle,
  IconAlignCenter,
  IconAlignJustify,
  IconAlignLeft,
  IconAlignRight,
  IconAnchor,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconArrowUUpLeft,
  IconArrowsClockwise,
  IconArrowsCounterClockwise,
  IconAt,
  IconBarChart,
  IconBarChart2,
  IconBarChart3,
  IconBattery,
  IconBell,
  IconBellRinging,
  IconBlock,
  IconBluetooth,
  IconBook,
  IconBookMarked,
  IconBookmark,
  IconBot,
  IconBox,
  IconBrackets,
  IconBrain,
  IconBriefcase,
  IconCalendar,
  IconCamera,
  IconChartLine,
  IconChartPie,
  IconChatCircle,
  IconChatSquare,
  IconCheck,
  IconCheckCheck,
  IconCheckCircle,
  IconCheckCircle2,
  IconChecklist,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleAlert,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleDot,
  IconCircleHelp,
  IconClock,
  IconClockCounterClockwise,
  IconCode,
  IconCode2,
  IconCommand,
  IconCompass,
  IconConstruction,
  IconCopy,
  IconCpu,
  IconCreditCard,
  IconCrop,
  IconCrosshair,
  IconDatabase,
  IconDeviceMobile,
  IconDiamond,
  IconDotsSixVertical,
  IconDotsThree,
  IconDotsThreeVertical,
  IconDownload,
  IconDribbble,
  IconEdit,
  IconEdit3,
  IconEraser,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFlame,
  IconFlaskConical,
  IconFolder,
  IconFolderOpen,
  IconFrown,
  IconFunnel,
  IconGauge,
  IconGear,
  IconGift,
  IconGitBranch,
  IconGitCommit,
  IconGitMerge,
  IconGitPullRequest,
  IconGithubLogo,
  IconGlobe,
  IconGraduationCap,
  IconGrid,
  IconGripVertical,
  IconHardDrive,
  IconHash,
  IconHeadphones,
  IconHeart,
  IconHelpCircle,
  IconHexagon,
  IconHistory,
  IconHome,
  IconHourglass,
  IconHourglassMedium,
  IconHouse,
  IconImage,
  IconInbox,
  IconInfo,
  IconKey,
  IconKeyRound,
  IconKeyboard,
  IconLanguages,
  IconLaptop,
  IconLayers,
  IconLayout,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconLifeBuoy,
  IconLightbulb,
  IconLightning,
  IconLightningSlash,
  IconLink,
  IconList,
  IconListChecks,
  IconListTree,
  IconLoader,
  IconLoader2,
  IconLock,
  IconLogIn,
  IconLogOut,
  IconMail,
  IconMagnifyingGlass,
  IconMap,
  IconMapPin,
  IconMaximize,
  IconMenu,
  IconMessageCircle,
  IconMessageCirclePlus,
  IconMessageSquare,
  IconMic,
  IconMicOff,
  IconMinimize,
  IconMinus,
  IconMonitor,
  IconMoon,
  IconMoreHorizontal,
  IconMoreVertical,
  IconMouse,
  IconMove,
  IconMusic,
  IconNavigation,
  IconNetwork,
  IconPackage,
  IconPalette,
  IconPanelRightOpen,
  IconPaperclip,
  IconPaperPlaneTilt,
  IconPause,
  IconPencil,
  IconPercent,
  IconPhone,
  IconPieChart,
  IconPin,
  IconPlay,
  IconPlug,
  IconPlus,
  IconPower,
  IconPrinter,
  IconQrCode,
  IconQuestion,
  IconRefreshCw,
  IconRepeat,
  IconRepeat2,
  IconReply,
  IconRocket,
  IconRotateCcw,
  IconRss,
  IconSave,
  IconScales,
  IconScan,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconShare,
  IconShareNetwork,
  IconShield,
  IconShieldAlert,
  IconShieldCheck,
  IconShieldOff,
  IconShieldSlash,
  IconWarningOctagon,
  IconShoppingBag,
  IconShoppingCart,
  IconShuffle,
  IconSidebar,
  IconSmile,
  IconSkipBack,
  IconSkipForward,
  IconSlackLogo,
  IconSliders,
  IconSmartphone,
  IconSparkle,
  IconSparkles,
  IconSpeakerHigh,
  IconSpeakerSimpleHigh,
  IconSpeakerSlash,
  IconSpinner,
  IconSpinnerGap,
  IconSquare,
  IconSquaresFour,
  IconStack,
  IconStar,
  IconStopCircle,
  IconSun,
  IconSunrise,
  IconTable,
  IconTablet,
  IconTag,
  IconTarget,
  IconTerminal,
  IconTestTube,
  IconTextT,
  IconThumbsDown,
  IconThumbsUp,
  IconTicket,
  IconTimer,
  IconToggleLeft,
  IconToggleRight,
  IconTrash,
  IconTrash2,
  IconTrashSimple,
  IconTrendDown,
  IconTrendUp,
  IconTrendingDown,
  IconTrendingUp,
  IconTreeStructure,
  IconTrelloLogo,
  IconTruck,
  IconTv,
  IconUmbrella,
  IconUnderline,
  IconUndo,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserCog,
  IconUserGear,
  IconUserCircleGear,
  IconUserMinus,
  IconUserPlus,
  IconUsers,
  IconVideo,
  IconVideoCamera,
  IconVideoCameraSlash,
  IconVideoOff,
  IconVolume,
  IconVolume2,
  IconVolumeX,
  IconWallet,
  IconWand,
  IconWand2,
  IconWatch,
  IconWaves,
  IconWifi,
  IconWifiHigh,
  IconWifiSlash,
  IconWind,
  IconWorkflow,
  IconWrench,
  IconX,
  IconXCircle,
  IconYoutube,
  IconYoutubeLogo,
  IconZap,
  IconZapOff,
} = icons;
